### ISSUE TITLE
How detectable is this plugin?

### ISSUE THREAD

**Issue by cupcake121** [UnknownX7/ARealmRecorded#2]
First of all i want to say i absolutely love the concept of this plugin but i do have a few concerns and finding info about the duty recorder is a bit of a pain in the butt. 

It is claimed that replay files are stored server-side however i'm not sure if that really makes sense considering it's possible to literally see the files in `Documents\My Games\FINAL FANTASY XIV - A Realm Reborn\replay`

However Yoshi-p claimed that Duty Recorder places a huge load on the server therefore it's limited to some very specific duties.
https://www.youtube.com/watch?v=p6dQf8CwQZg (4:20 onwards)

If the server load claim is true, using this plugin might be a bit too noticeable? 

Recording a duty requires consent from all other party members (or so i've read). Does this plugin skip the consent part? Cause it would be a bit unusual for other players if they suddenly get a "Do you want to be recorded?" message in a duty that does not normally allow for recording. 

Lastly, if my worries are unfounded would it be possible to re-implement gpose into the duty recorder? Seeing that slowmotion/fast forward was brought back by this plugin.

Thank you.

**Comment by UnknownX7** [comment]
The duty recorder is entirely clientside, I don't know why he claims otherwise. The only thing sent is a packet asking if you can enter a duty recording playback, which is only declined if sent from outside of an inn. The packet contains no information about the recording either.

This plugin skips the check and immediately activates the function called by the packet received after the ready check passes, upon entering a duty.

GPose depends on whether or not the server needs to confirm that you can enter it, as sending the request from inside the duty recorder would be a red flag (and also likely be declined). It would be much safer for a plugin to add a timescale slider to GPose instead if this is the case.

**Comment by UnknownX7** [comment]
33dd6f5c299f90127cdca4c0dfaa5ffb696a68c4
